#!/bin/bash
xrdb $HOME/.Xresources
chromium --no-sandbox &

# maximize window
dimensions=$(xdpyinfo | sed 's/^ *dimension * : *\([0-9]*x[0-9]*\).*/\1/p')
windowid=$(xdotool getwindowfocus)
xdotool windowmove "$windowid" 0 0 
xdotool windowsize "$windowid" 1280 720
